# Write your code here
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: NodePort
  ports:
  - name: "application"
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31111
  selector:
    project: kubernetes-project
    app: application
    tier: frontend