apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      project: kubernetes-project
      app: application
      tier: frontend
  template:
    metadata:
      labels:
        project: kubernetes-project
        app: application
        tier: frontend
    spec: 
      containers:
      - name: app-pod
        image: educative1/multiple_deployments:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
                name: database-configmap